#!/usr/bin/env python3
"""Render OpenTofu HCL for a VM from a YAML config.

Usage:
    python3 generator/generate.py [--config config/vm.yaml] [--out build]
"""

import argparse
import re
import sys
from pathlib import Path

import yaml
from jinja2 import Environment, FileSystemLoader, StrictUndefined

from providers import aws, gcp

REPO_ROOT = Path(__file__).resolve().parent.parent
TEMPLATE_DIR = Path(__file__).resolve().parent / "templates"

PROVIDERS = {"gcp": gcp, "aws": aws}

# OpenSSH public-key line: key type, base64 blob, optional comment.
PUBLIC_KEY_RE = re.compile(r"^(sk-)?(ssh|ecdsa)-[a-z0-9@.-]+\s+\S+", re.IGNORECASE)

# network.open_ports entry: optional tcp:/udp: prefix, port or low-high range.
OPEN_PORT_RE = re.compile(r"^(?:(tcp|udp):)?(\d{1,5})(?:-(\d{1,5}))?$")

# Optional provider marker in a generated main.tf's first line, e.g.
# "# Generated by ... — provider: aws — do not edit by hand.". The GCP
# template carries no marker; a marker-less file counts as GCP.
PROVIDER_MARKER_RE = re.compile(r"\bprovider:\s*([a-z0-9]+)\b")

# Settings every provider needs; each provider module adds its own
# (provider.REQUIRED_KEYS) on top.
REQUIRED_KEYS = [
    ("network", "name"),
    ("network", "ssh_source_ranges"),
    ("vm", "name"),
    ("vm", "machine_type"),
    ("vm", "boot_disk_gb"),
    ("vm", "boot_disk_type"),
    ("vm", "image"),
    ("vm", "ssh_user"),
]


def fail(msg: str) -> None:
    sys.exit(f"error: {msg}")


def get_provider(cfg: dict):
    name = cfg.get("provider", "gcp")
    if name not in PROVIDERS:
        fail(f"unknown provider {name!r}; valid: " + ", ".join(sorted(PROVIDERS)))
    return PROVIDERS[name]


def provider_call(fn, cfg):
    """Run a provider hook, turning its ValueError into a fatal error."""
    try:
        return fn(cfg)
    except ValueError as exc:
        fail(str(exc))


def example_hint(path: Path) -> str:
    """Suggest copying the committed example when a config file is missing."""
    example = REPO_ROOT / "config" / "examples" / path.name
    if not example.is_file():
        return ""
    try:
        target = path.relative_to(REPO_ROOT)
    except ValueError:
        target = path
    return f" (start from the example: cp config/examples/{path.name} {target})"


def load_config(path: Path) -> dict:
    try:
        cfg = yaml.safe_load(path.read_text())
    except FileNotFoundError:
        fail(f"config file not found: {path}{example_hint(path)}")
    except yaml.YAMLError as exc:
        fail(f"could not parse {path}: {exc}")
    if not isinstance(cfg, dict):
        fail(f"{path} must contain a YAML mapping")
    return cfg


def validate(cfg: dict, provider) -> None:
    provider_call(provider.apply_os_preset, cfg)

    for section, key in REQUIRED_KEYS + provider.REQUIRED_KEYS:
        if key not in cfg.get(section, {}):
            fail(f"missing required setting: {section}.{key}")

    vm = cfg["vm"]
    min_gb = vm.get("min_memory_gb", 64)
    machine_type = vm["machine_type"]
    ram_gb = provider.machine_ram_gb(machine_type)
    if ram_gb is not None:
        if ram_gb < min_gb:
            fail(
                f"machine_type {machine_type} has {ram_gb} GB RAM, "
                f"below the required {min_gb} GB"
            )
    else:
        print(
            f"warning: cannot infer RAM for machine_type {machine_type!r}; "
            f"verify it has at least {min_gb} GB",
            file=sys.stderr,
        )

    if vm["boot_disk_gb"] < 250:
        fail(f"boot_disk_gb is {vm['boot_disk_gb']}, below the required 250")

    ip_count = vm.setdefault("external_ip_count", 1)
    if (
        isinstance(ip_count, bool)
        or not isinstance(ip_count, int)
        or not 1 <= ip_count <= provider.MAX_EXTERNAL_IPS
    ):
        fail(
            f"vm.external_ip_count is {ip_count!r}; "
            f"must be an integer between 1 and {provider.MAX_EXTERNAL_IPS}"
        )

    nic_count = vm.setdefault("nic_count", 1)
    if (
        isinstance(nic_count, bool)
        or not isinstance(nic_count, int)
        or not 1 <= nic_count <= provider.MAX_NICS
    ):
        fail(
            f"vm.nic_count is {nic_count!r}; "
            f"must be an integer between 1 and {provider.MAX_NICS}"
        )

    provider_call(provider.validate, cfg)

    if not cfg["network"]["ssh_source_ranges"]:
        fail("network.ssh_source_ranges must list at least one CIDR")

    parse_open_ports(cfg["network"])


def parse_open_ports(network: dict) -> dict:
    """Group network.open_ports into GCP port strings, keyed by protocol."""
    entries = network.get("open_ports") or []
    if not isinstance(entries, list):
        fail("network.open_ports must be a list of ports")

    by_proto = {"tcp": [], "udp": []}
    for entry in entries:
        if isinstance(entry, int) and not isinstance(entry, bool):
            proto, low, high = "tcp", entry, None
        else:
            match = OPEN_PORT_RE.match(str(entry).strip())
            if not isinstance(entry, str) or not match:
                fail(
                    f"network.open_ports entry {entry!r} must be a port, a "
                    "low-high range, or either with a tcp:/udp: prefix"
                )
            proto = match.group(1) or "tcp"
            low = int(match.group(2))
            high = int(match.group(3)) if match.group(3) else None
        for port in (low, high):
            if port is not None and not 1 <= port <= 65535:
                fail(
                    f"network.open_ports entry {entry!r}: "
                    f"port {port} is outside 1-65535"
                )
        if high is not None and high < low:
            fail(f"network.open_ports range {entry!r} is backwards")
        by_proto[proto].append(str(low) if high is None else f"{low}-{high}")
    return by_proto


def key_file_path(setting: str) -> Path:
    """Expand ~ and resolve relative paths against the repo root."""
    path = Path(setting).expanduser()
    return path if path.is_absolute() else REPO_ROOT / path


def resolve_ssh_public_keys(vm: dict) -> list[str]:
    """Merge keys from all configured sources, in order, deduplicated."""
    keys: list[str] = []

    inline = vm.get("ssh_public_key")
    if inline:
        keys.append(inline.strip())

    for setting, multi in [("ssh_public_key_file", False),
                           ("ssh_public_keys_file", True)]:
        if not vm.get(setting):
            continue
        path = key_file_path(vm[setting])
        if not path.is_file():
            fail(f"vm.{setting}: file not found: {path}{example_hint(path)}")
        for line in path.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            keys.append(line)
            if not multi:
                break

    for key in keys:
        if not PUBLIC_KEY_RE.match(key):
            fail(f"this does not look like an OpenSSH public key: {key!r}")

    deduped = list(dict.fromkeys(keys))
    if not deduped:
        fail(
            "no SSH public keys found: set vm.ssh_public_key, "
            "vm.ssh_public_key_file, or add keys to vm.ssh_public_keys_file"
        )
    return deduped


def check_out_dir(out_dir: Path, provider, force: bool) -> None:
    """Refuse to render one provider's output over another's main.tf.

    The provider is read from the existing file's first-line marker; a
    file without a marker predates markers and is treated as GCP.
    """
    existing = out_dir / "main.tf"
    if force or not existing.is_file():
        return
    lines = existing.read_text().splitlines()
    match = PROVIDER_MARKER_RE.search(lines[0]) if lines else None
    existing_provider = match.group(1) if match else "gcp"
    if existing_provider != provider.NAME:
        fail(
            f"{existing} was generated for provider {existing_provider!r}, "
            f"not {provider.NAME!r}; refusing to overwrite it "
            "(use --force to override)"
        )


def render(cfg: dict, out_dir: Path, provider, force: bool = False) -> Path:
    check_out_dir(out_dir, provider, force)
    env = Environment(
        loader=FileSystemLoader(TEMPLATE_DIR),
        undefined=StrictUndefined,
        keep_trailing_newline=True,
    )
    hcl = env.get_template(f"{provider.TEMPLATE_SUBDIR}/main.tf.j2").render(
        **cfg,
        ssh_public_keys=resolve_ssh_public_keys(cfg["vm"]),
        open_ports=parse_open_ports(cfg["network"]),
        **provider.render_context(cfg),
    )
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir / "main.tf"
    out_file.write_text(hcl)
    return out_file


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--config", type=Path, default=REPO_ROOT / "config" / "vm.yaml"
    )
    parser.add_argument("--out", type=Path, default=REPO_ROOT / "build")
    parser.add_argument(
        "--force",
        action="store_true",
        help="overwrite an out directory whose main.tf names another provider",
    )
    args = parser.parse_args()

    cfg = load_config(args.config)
    provider = get_provider(cfg)
    validate(cfg, provider)
    out_file = render(cfg, args.out, provider, force=args.force)
    print(f"wrote {out_file}")
    print(f"next: tofu -chdir={args.out} init && tofu -chdir={args.out} apply")


if __name__ == "__main__":
    main()
